name: Auto Update Data

on:
  schedule:
    - cron: "0 15 * * *" #每日00:00(JST)執行
    - cron: "0 8 * * 3,4" #每週三四17:00(JST)執行
    - cron: "*/20 5-6 * * 4" #每週四14-15:00(JST)，每20分鐘執行 (通常實裝時段)
    - cron: "0 2 * * 5" #每週五11:00(JST)執行 (卡池正式登場前1小時)
  workflow_dispatch: #允許手動觸發

permissions:
  contents: write

jobs:
  Auto-Update-Data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check last update time
        run: |
          if [ -f "lastUpdate" ] && [ $(( $(date +%s) - $(cat "lastUpdate") )) -lt 3600 ]; then
            echo "SKIP_JOB=true" >> $GITHUB_ENV
            echo "Last update within 1 hour, skip!"
            exit 0
          fi

      # - name: Check files changed
      #   if: env.SKIP_JOB != 'true'
      #   run: |
      #     localization_local="Localization/FileHashes.json"
      #     localization_remote="https://prd.evertaleserver.com/Prd300/Localization/FileHashes.json"
      #     if [ ! -f "$localization_local" ] || [ "$(curl -s "$localization_remote")" != "$(cat "$localization_local")" ]; then
      #       echo "SKIP_JOB=false" >> $GITHUB_ENV
      #       exit 0
      #     fi

      #     manifest_local="Config/Manifest.json"
      #     manifest_remote="https://prd.evertaleserver.com/Prd300/Manifest.json"
      #     if [ ! -f "$manifest_local" ] || [ "$(curl -s "$manifest_remote")" != "$(cat "$manifest_local")" ]; then
      #       echo "SKIP_JOB=false" >> $GITHUB_ENV
      #       exit 0
      #     fi

      #     echo "SKIP_JOB=true" >> $GITHUB_ENV
      #     echo "No changes, skip!"

      - name: Setup Node.js
        if: env.SKIP_JOB != 'true'
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run script
        if: env.SKIP_JOB != 'true'
        env:
          LOGIN_ACCOUNT_INFO: ${{secrets.LOGIN_ACCOUNT_INFO}}
        run: node UpdateData.js

      - name: Commit and push changes
        if: env.SKIP_JOB != 'true'
        run: |
          git add Localization/ Config/ Collection/
          if git diff --cached --quiet; then
            echo "No changes"
          else
            printf "%s" "$(date +%s)" > lastUpdate
            git add lastUpdate
            git config user.name "Evertale-PlayerTW[bot]"
            git config user.email "213433941+Evertale-PlayerTW@users.noreply.github.com"
            git commit -m "Auto update: $(date -u +"%Y-%m-%d %H:%M:%S")"
            git push
          fi
